config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :leads
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'leads#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :leads 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /leads or /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1 or /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    
    #@lead = Lead.new
    @lead = current_user.leads.build 

  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads or /leads.json
  def create
    #@lead = Lead.new(lead_params)
    @lead = current_user.leads.build(lead_params)
    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: "Lead was successfully created." }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: "Lead was successfully updated." }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: "Lead was successfully destroyed." }
      format.json { head :no_content }
    end
  end

def correct_user

  @lead = current_user.leads.find_by(id: params[:id])
  redirect_to leads_path, notice: "Not Authorized To Edit This Lead" if @lead.nil?

end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.require(:lead).permit(:first_name, :last_name, :email, :phone, :salary, :comments, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

<%=link_to "Leads" , root_path,class:"navbar-brand" %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
        	<%=link_to "About Us" ,home_about_path,class:"nav-link" %>

        </li>
        
        


        <% if user_signed_in? %> 

          <%=link_to "Log Out" ,destroy_user_session_path,method: :delete,class:"nav-link" %>
          </li>

          <li class="nav-item">
          <%=link_to "Edit Profile" ,edit_user_registration_path,class:"nav-link" %>

<!-- 
          <li class="nav-item">
          <%=link_to "Add Lead" ,new_lead_path,class:"nav-link" %>
          </li> -->

         <!--  <li class="nav-item">
          <%=link_to "Leads" ,leads_path,class:"nav-link" %>
          </li> -->

         <% else %> 

          <li class="nav-item">
          <%=link_to "Sign Up" ,new_user_registration_path,class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%=link_to "Login" , new_user_session_path,class:"nav-link" %>
          </li>
          <li class="nav-item">
          <% end %>





          
          
        

        </li>
       
      </ul>
      <form class="d-flex">
        
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>about us....</h1>

app/views/home/index.html.erb
<p>Home....</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice  %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Leads</title>


     <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <br/>

    <%= render 'home/header' %>
    <div class = "container">

   <br/>
    

    <% if notice  %>
      <%= render 'layouts/alerts' %>
    <% end %>
    
    <%= yield %>
    
    
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/leads/_form.html.erb
<%= form_with(model: lead) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  

  <div class="field form-group">
    <br><br>
    <%= form.text_field :first_name ,class:"form-control",placeholder:"First Name"%> <br>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name ,class:"form-control",placeholder:"Last Name"%><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :email,class:"form-control",placeholder:"Email Id" %><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone,class:"form-control",placeholder:"Phone Number" %><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :salary,class:"form-control",placeholder:"Salary" %><br>
  </div>

  <div class="field form-group">
    <%= form.text_field :comments,class:"form-control" ,placeholder:"Comments"%><br>
  </div>

   <div class="field form-group">
    <%= form.number_field :user_id,class:"form-control",id: :friend_user_id,value:current_user.id , type: :hidden%><br>
  </div>




  <div class="actions">
    <br>
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Edit Lead</h4>
  </div>
  <div class="card-body">

<%= render 'form', lead: @lead %>

<br>
<pre><%= link_to 'Show', @lead ,class:"btn btn-secondary"  %>  <%= link_to 'Back', leads_path,class:"btn btn-secondary" %></pre>


</div>
</div>

app/views/leads/index.html.erb
<table class = "table table-striped table-bordered table-hover">
  <thead class="table-dark">


<%  if user_signed_in? %>

 <br>
 <br>


    <tr>


      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Salary</th>
      <th>Comments</th>
      <!-- <th>User ID</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >

      
    <% @leads.each do |lead| %>

    <% if lead.user == current_user %>
      <tr>
        <td>
          
               <%= link_to lead.first_name, lead ,style:"text-decoration:none;"%>
               <%= link_to lead.last_name, lead ,style:"text-decoration:none;"%>


             </td>
        <td><%= lead.email %></td>
        <td><%= lead.phone %></td>
        <td><%= lead.salary %></td>
        <td><%= lead.comments %></td>
        
       <!--  <td><%= lead.user_id %></td> -->

        <td><button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Edit', edit_lead_path(lead),style:"text-decoration:none;" %></button></td>

                <td><button type="button" class="btn btn-outline-danger btn-sm"><%= link_to 'Delete', edit_lead_path(lead),style:"text-decoration:none;" %></button></td>


      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path,style:"text-decoration:none;",class:"btn btn-secondary" %>


<% else %>



<p>Home....</p>

<% end %>

app/views/leads/new.html.erb
<h1>Add New Lead</h1>

<%= render 'form', lead: @lead %> 
<br>

<%= link_to 'Back', leads_path  ,class:"btn btn-secondary"%>

app/views/leads/show.html.erb
<div class="card">
  <div class="card-header">
    Lead
  </div>
  <div class="card-body">
    <h1 class="card-title"><%= @lead.first_name %> <%= @lead.last_name %> </h1>
    <p> Comments:  <%= @lead.comments %> </p>
    <pre class="card-text"> Email ID: <%= @lead.email %>          Phone Number: <%= @lead.phone %>            Salary: <%= @lead.salary %>$</pre>


    <%= link_to 'Edit', edit_lead_path(@lead),class:"btn btn-secondary"%> 
<%= link_to 'Back', leads_path,class:"btn btn-secondary" %>
  </div>
</div>